/*
 * Leviathan api
 *
 * OpenAPI spec for leviathan
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package serverstub

type DockerImagesGet200Response struct {

	// List of images
	Images []DockerImage `json:"images,omitempty"`
}
