/* tslint:disable */
/* eslint-disable */
/**
 * Leviathan api
 * OpenAPI spec for leviathan
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface DeleteCourse
 */
export interface DeleteCourse {
    /**
     * ID the course
     * @type {string}
     * @memberof DeleteCourse
     */
    'ID': string;
}
/**
 * 
 * @export
 * @interface DockerImage
 */
export interface DockerImage {
    /**
     * Tag name
     * @type {string}
     * @memberof DockerImage
     */
    'tag'?: string;
}
/**
 * 
 * @export
 * @interface DockerImagesCreatePost200Response
 */
export interface DockerImagesCreatePost200Response {
    /**
     * Logs generated when image was built
     * @type {string}
     * @memberof DockerImagesCreatePost200Response
     */
    'logs'?: string;
    /**
     * 
     * @type {string}
     * @memberof DockerImagesCreatePost200Response
     */
    'tagName'?: string;
}
/**
 * 
 * @export
 * @interface DockerImagesGet200Response
 */
export interface DockerImagesGet200Response {
    /**
     * List of images
     * @type {Array<DockerImage>}
     * @memberof DockerImagesGet200Response
     */
    'images'?: Array<DockerImage>;
}
/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponse
     */
    'reason'?: string;
}

/**
 * CoursesApi - axios parameter creator
 * @export
 */
export const CoursesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Deletes a course
         * @param {string} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseCourseIdDelete: async (courseId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseId' is not null or undefined
            assertParamExists('courseCourseIdDelete', 'courseId', courseId)
            const localVarPath = `/course/{courseId}`
                .replace(`{${"courseId"}}`, encodeURIComponent(String(courseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List all courses
         * @param {string} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseCourseIdGet: async (courseId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseId' is not null or undefined
            assertParamExists('courseCourseIdGet', 'courseId', courseId)
            const localVarPath = `/course/{courseId}`
                .replace(`{${"courseId"}}`, encodeURIComponent(String(courseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Edit course
         * @param {string} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseCourseIdPatch: async (courseId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseId' is not null or undefined
            assertParamExists('courseCourseIdPatch', 'courseId', courseId)
            const localVarPath = `/course/{courseId}`
                .replace(`{${"courseId"}}`, encodeURIComponent(String(courseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new course with the associated image name, Makefile, and grading file
         * @param {File} tarfile 
         * @param {string} courseName The name of the tar file being uploaded
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursePost: async (tarfile: File, courseName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tarfile' is not null or undefined
            assertParamExists('coursePost', 'tarfile', tarfile)
            // verify required parameter 'courseName' is not null or undefined
            assertParamExists('coursePost', 'courseName', courseName)
            const localVarPath = `/course`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (tarfile !== undefined) { 
                localVarFormParams.append('tarfile', tarfile as any);
            }
    
            if (courseName !== undefined) { 
                localVarFormParams.append('courseName', courseName as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CoursesApi - functional programming interface
 * @export
 */
export const CoursesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CoursesApiAxiosParamCreator(configuration)
    return {
        /**
         * Deletes a course
         * @param {string} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async courseCourseIdDelete(courseId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.courseCourseIdDelete(courseId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.courseCourseIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List all courses
         * @param {string} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async courseCourseIdGet(courseId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.courseCourseIdGet(courseId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.courseCourseIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Edit course
         * @param {string} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async courseCourseIdPatch(courseId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.courseCourseIdPatch(courseId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.courseCourseIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new course with the associated image name, Makefile, and grading file
         * @param {File} tarfile 
         * @param {string} courseName The name of the tar file being uploaded
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coursePost(tarfile: File, courseName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coursePost(tarfile, courseName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.coursePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CoursesApi - factory interface
 * @export
 */
export const CoursesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CoursesApiFp(configuration)
    return {
        /**
         * Deletes a course
         * @param {string} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseCourseIdDelete(courseId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.courseCourseIdDelete(courseId, options).then((request) => request(axios, basePath));
        },
        /**
         * List all courses
         * @param {string} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseCourseIdGet(courseId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.courseCourseIdGet(courseId, options).then((request) => request(axios, basePath));
        },
        /**
         * Edit course
         * @param {string} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseCourseIdPatch(courseId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.courseCourseIdPatch(courseId, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new course with the associated image name, Makefile, and grading file
         * @param {File} tarfile 
         * @param {string} courseName The name of the tar file being uploaded
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coursePost(tarfile: File, courseName: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.coursePost(tarfile, courseName, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CoursesApi - object-oriented interface
 * @export
 * @class CoursesApi
 * @extends {BaseAPI}
 */
export class CoursesApi extends BaseAPI {
    /**
     * Deletes a course
     * @param {string} courseId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public courseCourseIdDelete(courseId: string, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).courseCourseIdDelete(courseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List all courses
     * @param {string} courseId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public courseCourseIdGet(courseId: string, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).courseCourseIdGet(courseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Edit course
     * @param {string} courseId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public courseCourseIdPatch(courseId: string, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).courseCourseIdPatch(courseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new course with the associated image name, Makefile, and grading file
     * @param {File} tarfile 
     * @param {string} courseName The name of the tar file being uploaded
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public coursePost(tarfile: File, courseName: string, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).coursePost(tarfile, courseName, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DockerApi - axios parameter creator
 * @export
 */
export const DockerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Stops and deletes a container
         * @param {number} containerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dockerContainerIdDelete: async (containerId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'containerId' is not null or undefined
            assertParamExists('dockerContainerIdDelete', 'containerId', containerId)
            const localVarPath = `/docker/{containerId}`
                .replace(`{${"containerId"}}`, encodeURIComponent(String(containerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets the container info based on ID
         * @param {string} containerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dockerContainerIdGet: async (containerId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'containerId' is not null or undefined
            assertParamExists('dockerContainerIdGet', 'containerId', containerId)
            const localVarPath = `/docker/{containerId}`
                .replace(`{${"containerId"}}`, encodeURIComponent(String(containerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Start the container based on ID
         * @param {number} containerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dockerContainerIdStartGet: async (containerId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'containerId' is not null or undefined
            assertParamExists('dockerContainerIdStartGet', 'containerId', containerId)
            const localVarPath = `/docker/{containerId}/start`
                .replace(`{${"containerId"}}`, encodeURIComponent(String(containerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Stops the container based on ID
         * @param {number} containerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dockerContainerIdStopGet: async (containerId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'containerId' is not null or undefined
            assertParamExists('dockerContainerIdStopGet', 'containerId', containerId)
            const localVarPath = `/docker/{containerId}/stop`
                .replace(`{${"containerId"}}`, encodeURIComponent(String(containerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a image from a dockerfile
         * @param {File} dockerFile 
         * @param {string} tagName The name of the tar file being uploaded
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dockerImagesCreatePost: async (dockerFile: File, tagName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dockerFile' is not null or undefined
            assertParamExists('dockerImagesCreatePost', 'dockerFile', dockerFile)
            // verify required parameter 'tagName' is not null or undefined
            assertParamExists('dockerImagesCreatePost', 'tagName', tagName)
            const localVarPath = `/docker/images/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (dockerFile !== undefined) { 
                localVarFormParams.append('dockerFile', dockerFile as any);
            }
    
            if (tagName !== undefined) { 
                localVarFormParams.append('tagName', tagName as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List all images from a dockerfile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dockerImagesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/docker/images`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DockerApi - functional programming interface
 * @export
 */
export const DockerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DockerApiAxiosParamCreator(configuration)
    return {
        /**
         * Stops and deletes a container
         * @param {number} containerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dockerContainerIdDelete(containerId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dockerContainerIdDelete(containerId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DockerApi.dockerContainerIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets the container info based on ID
         * @param {string} containerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dockerContainerIdGet(containerId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dockerContainerIdGet(containerId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DockerApi.dockerContainerIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Start the container based on ID
         * @param {number} containerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dockerContainerIdStartGet(containerId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dockerContainerIdStartGet(containerId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DockerApi.dockerContainerIdStartGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Stops the container based on ID
         * @param {number} containerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dockerContainerIdStopGet(containerId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dockerContainerIdStopGet(containerId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DockerApi.dockerContainerIdStopGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a image from a dockerfile
         * @param {File} dockerFile 
         * @param {string} tagName The name of the tar file being uploaded
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dockerImagesCreatePost(dockerFile: File, tagName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DockerImagesCreatePost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dockerImagesCreatePost(dockerFile, tagName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DockerApi.dockerImagesCreatePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List all images from a dockerfile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dockerImagesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DockerImagesGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dockerImagesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DockerApi.dockerImagesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DockerApi - factory interface
 * @export
 */
export const DockerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DockerApiFp(configuration)
    return {
        /**
         * Stops and deletes a container
         * @param {number} containerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dockerContainerIdDelete(containerId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.dockerContainerIdDelete(containerId, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets the container info based on ID
         * @param {string} containerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dockerContainerIdGet(containerId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.dockerContainerIdGet(containerId, options).then((request) => request(axios, basePath));
        },
        /**
         * Start the container based on ID
         * @param {number} containerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dockerContainerIdStartGet(containerId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.dockerContainerIdStartGet(containerId, options).then((request) => request(axios, basePath));
        },
        /**
         * Stops the container based on ID
         * @param {number} containerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dockerContainerIdStopGet(containerId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.dockerContainerIdStopGet(containerId, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a image from a dockerfile
         * @param {File} dockerFile 
         * @param {string} tagName The name of the tar file being uploaded
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dockerImagesCreatePost(dockerFile: File, tagName: string, options?: RawAxiosRequestConfig): AxiosPromise<DockerImagesCreatePost200Response> {
            return localVarFp.dockerImagesCreatePost(dockerFile, tagName, options).then((request) => request(axios, basePath));
        },
        /**
         * List all images from a dockerfile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dockerImagesGet(options?: RawAxiosRequestConfig): AxiosPromise<DockerImagesGet200Response> {
            return localVarFp.dockerImagesGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DockerApi - object-oriented interface
 * @export
 * @class DockerApi
 * @extends {BaseAPI}
 */
export class DockerApi extends BaseAPI {
    /**
     * Stops and deletes a container
     * @param {number} containerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DockerApi
     */
    public dockerContainerIdDelete(containerId: number, options?: RawAxiosRequestConfig) {
        return DockerApiFp(this.configuration).dockerContainerIdDelete(containerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets the container info based on ID
     * @param {string} containerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DockerApi
     */
    public dockerContainerIdGet(containerId: string, options?: RawAxiosRequestConfig) {
        return DockerApiFp(this.configuration).dockerContainerIdGet(containerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Start the container based on ID
     * @param {number} containerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DockerApi
     */
    public dockerContainerIdStartGet(containerId: number, options?: RawAxiosRequestConfig) {
        return DockerApiFp(this.configuration).dockerContainerIdStartGet(containerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Stops the container based on ID
     * @param {number} containerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DockerApi
     */
    public dockerContainerIdStopGet(containerId: number, options?: RawAxiosRequestConfig) {
        return DockerApiFp(this.configuration).dockerContainerIdStopGet(containerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a image from a dockerfile
     * @param {File} dockerFile 
     * @param {string} tagName The name of the tar file being uploaded
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DockerApi
     */
    public dockerImagesCreatePost(dockerFile: File, tagName: string, options?: RawAxiosRequestConfig) {
        return DockerApiFp(this.configuration).dockerImagesCreatePost(dockerFile, tagName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List all images from a dockerfile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DockerApi
     */
    public dockerImagesGet(options?: RawAxiosRequestConfig) {
        return DockerApiFp(this.configuration).dockerImagesGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * StatsApi - axios parameter creator
 * @export
 */
export const StatsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StatsApi - functional programming interface
 * @export
 */
export const StatsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StatsApiAxiosParamCreator(configuration)
    return {
        /**
         * Stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async statsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.statsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.statsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StatsApi - factory interface
 * @export
 */
export const StatsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StatsApiFp(configuration)
    return {
        /**
         * Stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.statsGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StatsApi - object-oriented interface
 * @export
 * @class StatsApi
 * @extends {BaseAPI}
 */
export class StatsApi extends BaseAPI {
    /**
     * Stats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StatsApi
     */
    public statsGet(options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).statsGet(options).then((request) => request(this.axios, this.basePath));
    }
}



