/*
 * Leviathan api
 *
 * OpenAPI spec for leviathan
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package serverstub

import (
	"github.com/gin-gonic/gin"
)

type DockerAPI interface {

	// DockerContainerIdDelete Delete /docker/:containerId
	DockerContainerIdDelete(c *gin.Context)

	// DockerContainerIdGet Get /docker/:containerId
	DockerContainerIdGet(c *gin.Context)

	// DockerContainerIdStartGet Get /docker/:containerId/start
	DockerContainerIdStartGet(c *gin.Context)

	// DockerContainerIdStopGet Get /docker/:containerId/stop
	DockerContainerIdStopGet(c *gin.Context)

	// DockerImagesCreatePost Post /docker/images/create
	DockerImagesCreatePost(c *gin.Context)

	// DockerImagesGet Get /docker/images
	DockerImagesGet(c *gin.Context)
}
