/*
 * Leviathan api
 *
 * OpenAPI spec for leviathan
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package serverstub

import (
	"github.com/gin-gonic/gin"
)

type CoursesAPI interface {

	// CourseCourseIdDelete Delete /course/:courseId
	CourseCourseIdDelete(c *gin.Context)

	// CourseCourseIdGet Get /course/:courseId
	CourseCourseIdGet(c *gin.Context)

	// CourseCourseIdPatch Patch /course/:courseId
	CourseCourseIdPatch(c *gin.Context)

	// CoursePost Post /course
	CoursePost(c *gin.Context)
}
