/*
 * Leviathan api
 *
 * OpenAPI spec for leviathan
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package serverstub

type DockerImage struct {

	// Tag name
	Tag string `json:"tag,omitempty"`
}
