openapi: 3.0.3
info:
  title: Leviathan api
  description: OpenAPI .spec for leviathan
  version: 1.0.0

servers:
  - url: 'http://localhost:9221'

tags:
  - name: Courses
    description: Operation for managing courses
  - name: Jobs
    description: Creating and managing jobs
  - name: docker
    description: Operations for controlling docker
  - name: stats
    description: Operations related to stats

paths:
  # Course stuff
  /course:
    post:
      description: Create a new course with the associated image name, Makefile, and grading file
      tags:
        - Courses
      requestBody:
        description: Input the course name, docker image and tarfile
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateCourse'
      responses:
        200:
          description: Successful response

  /course/{courseId}:
    parameters:
      - in: path
        name: courseId
        required: true
        schema:
          type: string
    delete:
      description: Deletes a course
      responses:
        200:
          description: Response with the course ID
      #          content:
      #            application/json:
      #              schema:
      tags:
        - Courses
    patch:
      description: Edit course
      tags:
        - Courses
      responses:
        200:
          description: "Success"
    get:
      description: List all courses
      tags:
        - Courses
      responses:
        200:
          description: "Success"

  # Job stuff

  # Docker stuff
  /docker/images/create:
    post:
      tags:
        - docker
      description: Create a image from a dockerfile
      requestBody:
        description: Input the Dockerfile, tag name
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/CreateImage"
      responses:
        200:
          description: Successful creation
          content:
            application/json:
              schema:
                type: object
                properties:
                  logs:
                    description: Logs generated when image was built
                    type: string
                  tagName:
                    type: string
        400:
          description: Error creating image
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /docker/images:
    get:
      tags:
        - docker
      description: List all images from a dockerfile
      responses:
        200:
          description: List of images
          content:
            application/json:
              schema:
                type: object
                properties:
                  images:
                    description: List of images
                    type: array
                    items:
                      $ref: "#/components/schemas/DockerImage"
        400:
          description: Error listing image
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /docker/{containerId}:
    get:
      parameters:
        - in: path
          name: containerId
          required: true
          schema:
            type: string
      description: Gets the container info based on ID
      tags:
        - docker
      responses:
        400:
          description: Error listing image
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      parameters:
        - in: path
          name: containerId
          required: true
          schema:
            type: integer
      description: Stops and deletes a container
      tags:
        - docker
      responses:
        400:
          description: Error listing image
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /docker/{containerId}/start:
    get:
      parameters:
        - in: path
          name: containerId
          required: true
          schema:
            type: integer
      description: Start the container based on ID
      tags:
        - docker
      responses:
        400:
          description: Error listing image
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /docker/{containerId}/stop:
    get:
      parameters:
        - in: path
          name: containerId
          required: true
          schema:
            type: integer
      description: Stops the container based on ID
      tags:
        - docker
      responses:
        400:
          description: Error listing image
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  # stats
  /stats:
    get:
      description: Stats
      #      parameters:
      #        - in: path
      #          name: containerId
      #          required: true
      #          schema:
      #            type:
      tags:
        - stats
      responses:
        400:
          description: Error getting stats
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    CreateCourse:
      type: object
      properties:
        tarfile:
          type: string
          format: binary
        courseName:
          type: string
          description: The name of the tar file being uploaded
      required:
        - tarfile
        - courseName

    DeleteCourse:
      type: object
      required:
        - ID
      properties:
        ID:
          type: string
          description: ID the course

    DockerImage:
      type: object
      properties:
        tag:
          type: string
          description: Tag name

    CreateImage:
      type: object
      properties:
        dockerFile:
          type: string
          format: binary
        tagName:
          type: string
          description: The name of the tar file being uploaded
      required:
        - dockerFile
        - tagName

    ErrorResponse:
      type: object
      properties:
        reason:
          type: string
