/*
 * Leviathan api
 *
 * OpenAPI spec for leviathan
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package serverstub

import (
	"github.com/gin-gonic/gin"
)

type StatsAPI interface {

	// StatsGet Get /stats
	StatsGet(c *gin.Context)
}
