# Builds leviathan images on master

name: Build master
on:
  push:
    branches:
      - master
    paths:
      - '.github/**'
      - 'src/**'

  pull_request:
    branches:
      - master
    paths:
      - '.github/**'
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Dependencies
        run: go mod tidy

      - name: Run client manager tests
        working-directory: src/service/docker
        run: go test -v

      - name: Run client manager tests
        working-directory: src/service/tests
        # tests meant for CI
        run: |
          CI=true go test -v 
  

  build-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write # to be able to publish docker images
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # docker image build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: build and push leviathan
        run: |
          REGISTRY="ghcr.io/${{ github.repository }}"
          VERSION="${{ steps.tagName.outputs.tag }}"
          docker build . -t ${REGISTRY}:master
          docker push ${REGISTRY}:master

#      - name: build and push hydra
#        working-directory: hydra
#        run: |
#          REGISTRY="ghcr.io/makeopensource/hydra"
#          docker build . -t ${REGISTRY}:master
#          docker push ${REGISTRY}:master
